export const SET_INTERFACE_EDITOR_STYLE_EDITOR_INPUT_BORDER_CORNERS_INPUT_SELECTED_CORNERS = 'SET_INTERFACE_EDITOR_STYLE_EDITOR_INPUT_BORDER_CORNERS_INPUT_SELECTED_CORNERS';

export function setInterfaceEditorStyleEditorInputBorderCornersInputSelectedCorners(selectedCorners) {
  return {
    type: SET_INTERFACE_EDITOR_STYLE_EDITOR_INPUT_BORDER_CORNERS_INPUT_SELECTED_CORNERS,
    selectedCorners,
  };
}
