import { combineReducers } from 'redux';

// (App reducers)
import interfaceEditorComponent from './interfaceEditorComponent';
import interfaceEditorSelectedComponentKey from './interfaceEditorSelectedComponentKey';
import interfaceEditorSelectedElementPath from './interfaceEditorSelectedElementPath';
import interfaceEditorCanvasDevice from './interfaceEditorCanvasDevice';
import interfaceEditorCanvasOrientation from './interfaceEditorCanvasOrientation';
import interfaceEditorCanvasZoom from './interfaceEditorCanvasZoom';
import interfaceEditorDirectSelectModeEnabled from './interfaceEditorDirectSelectModeEnabled';
import interfaceEditorFullscreenPreview from './interfaceEditorFullscreenPreview';
import interfaceEditorWorkspacePanelModalContent from './interfaceEditorWorkspacePanelModalContent';
import interfaceEditorInspectorSelectedTabIndex from './interfaceEditorInspectorSelectedTabIndex';
import interfaceEditorInspectorStyleEditorSelectedProp from './interfaceEditorInspectorStyleEditorSelectedProp';
import interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides from './interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides from './interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides from './interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners from './interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners';
import interfaceEditorInspectorTreeNavigatorCollapsedElementPaths from './interfaceEditorInspectorTreeNavigatorCollapsedElementPaths';

const reducer = combineReducers({
  interfaceEditorComponent,
  interfaceEditorSelectedComponentKey,
  interfaceEditorSelectedElementPath,
  interfaceEditorCanvasDevice,
  interfaceEditorCanvasOrientation,
  interfaceEditorCanvasZoom,
  interfaceEditorDirectSelectModeEnabled,
  interfaceEditorFullscreenPreview,
  interfaceEditorWorkspacePanelModalContent,
  interfaceEditorInspectorSelectedTabIndex,
  interfaceEditorInspectorStyleEditorSelectedProp,
  interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners,
  interfaceEditorInspectorTreeNavigatorCollapsedElementPaths,
});

export default reducer;
