import { combineReducers } from 'redux';

// (App reducers)
import interfaceEditorComponents from './interfaceEditorComponents';
import interfaceEditorSelectedComponentKey from './interfaceEditorSelectedComponentKey';
import interfaceEditorSelectedElementPath from './interfaceEditorSelectedElementPath';
import interfaceEditorCanvasDevice from './interfaceEditorCanvasDevice';
import interfaceEditorCanvasOrientation from './interfaceEditorCanvasOrientation';
import interfaceEditorCanvasZoom from './interfaceEditorCanvasZoom';
import interfaceEditorDirectSelectModeEnabled from './interfaceEditorDirectSelectModeEnabled';
import interfaceEditorFullscreenPreview from './interfaceEditorFullscreenPreview';
import interfaceEditorWorkspacePanelModalContent from './interfaceEditorWorkspacePanelModalContent';
import interfaceEditorInspectorSelectedTabIndex from './interfaceEditorInspectorSelectedTabIndex';
import interfaceEditorInspectorStyleEditorSelectedProp from './interfaceEditorInspectorStyleEditorSelectedProp';
import interfaceEditorInspectorStyleEditorInputCollapsedSections from './interfaceEditorInspectorStyleEditorInputCollapsedSections';
import interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides from './interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides from './interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides from './interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides';
import interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners from './interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners';

const reducer = combineReducers({
  interfaceEditorComponents,
  interfaceEditorSelectedComponentKey,
  interfaceEditorSelectedElementPath,
  interfaceEditorCanvasDevice,
  interfaceEditorCanvasOrientation,
  interfaceEditorCanvasZoom,
  interfaceEditorDirectSelectModeEnabled,
  interfaceEditorFullscreenPreview,
  interfaceEditorWorkspacePanelModalContent,
  interfaceEditorInspectorSelectedTabIndex,
  interfaceEditorInspectorStyleEditorSelectedProp,
  interfaceEditorInspectorStyleEditorInputCollapsedSections,
  interfaceEditorInspectorStyleEditorInputMarginInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputPaddingInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputBorderSidesInputSelectedSides,
  interfaceEditorInspectorStyleEditorInputBorderCornersInputSelectedCorners,
});

export default reducer;
