// preview
export const BEGIN_FULL_SCREEN_PREVIEW = 'BEGIN_FULL_SCREEN_PREVIEW';
export const END_FULL_SCREEN_PREVIEW = 'END_FULL_SCREEN_PREVIEW';

// inspector
export const PUSH_INSPECTOR_ROUTE = 'PUSH_INSPECTOR_ROUTE';
export const POP_INSPECTOR_ROUTE = 'POP_INSPECTOR_ROUTE';
export const REPLACE_INSPECTOR_ROUTE = 'REPLACE_INSPECTOR_ROUTE';

// tree
export const ADD_ELEMENT_CHILD = 'ADD_ELEMENT_CHILD';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const CHANGE_ELEMENT_PATH = 'CHANGE_ELEMENT_PATH';
export const APPLY_ELEMENT_PROP = 'APPLY_ELEMENT_PROP';
export const REMOVE_ELEMENT_PROP = 'REMOVE_ELEMENT_PROP';
export const REDO_TREE_ACTION = 'REDO_TREE_ACTION';
export const UNDO_TREE_ACTION = 'UNDO_TREE_ACTION';
