// preview
export const BEGIN_FULL_SCREEN_PREVIEW = 'BEGIN_FULL_SCREEN_PREVIEW';
export const END_FULL_SCREEN_PREVIEW = 'END_FULL_SCREEN_PREVIEW';

// inspector
export const SELECT_ELEMENT_PATH = 'SELECT_ELEMENT_PATH';
export const EDIT_ELEMENT_PROP = 'EDIT_ELEMENT_PROP';
export const CREATE_ELEMENT_CHILD = 'CREATE_ELEMENT_CHILD';

// tree
export const ADD_ELEMENT_CHILD = 'ADD_ELEMENT_CHILD';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const CHANGE_ELEMENT_PATH = 'CHANGE_ELEMENT_PATH';
export const APPLY_ELEMENT_PROP = 'APPLY_ELEMENT_PROP';
export const REMOVE_ELEMENT_PROP = 'REMOVE_ELEMENT_PROP';
