// editor
export const SHOW_ADD_ELEMENT_MODAL = 'SHOW_ADD_ELEMENT_MODAL';
export const HIDE_ADD_ELEMENT_MODAL = 'HIDE_ADD_ELEMENT_MODAL';
export const SET_SELECTED_ELEMENT_PATH = 'SET_SELECTED_ELEMENT_PATH';
export const RESET_SELECTED_ELEMENT_PATH = 'RESET_SELECTED_ELEMENT_PATH';

// inspector
export const SET_SELECTED_INSPECTOR_TAB = 'SET_SELECTED_INSPECTOR_TAB';

// tree
export const ADD_ELEMENT_CHILD = 'ADD_ELEMENT_CHILD';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const HIDE_ELEMENT = 'HIDE_ELEMENT';
export const CHANGE_ELEMENT_PATH = 'CHANGE_ELEMENT_PATH';
export const APPLY_ELEMENT_PROP = 'APPLY_ELEMENT_PROP';
export const REMOVE_ELEMENT_PROP = 'REMOVE_ELEMENT_PROP';
export const REDO_TREE_ACTION = 'REDO_TREE_ACTION';
export const UNDO_TREE_ACTION = 'UNDO_TREE_ACTION';

// workspace
export const BEGIN_FULL_SCREEN_PREVIEW = 'BEGIN_FULL_SCREEN_PREVIEW';
export const END_FULL_SCREEN_PREVIEW = 'END_FULL_SCREEN_PREVIEW';
export const SET_CANVAS_DEVICE = 'SET_CANVAS_DEVICE';
export const SET_CANVAS_ORIENTATION = 'SET_CANVAS_ORIENTATION';
export const SET_CANVAS_ZOOM = 'SET_CANVAS_ZOOM';
